# Generated by Django 3.2 on 2022-06-17 10:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('manager_number', models.CharField(blank=True, max_length=20)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('hospital_name', models.CharField(blank=True, max_length=100)),
                ('hospital_number', models.CharField(blank=True, max_length=20)),
                ('hospital_email', models.EmailField(blank=True, max_length=254)),
                ('police_name', models.CharField(blank=True, max_length=100)),
                ('police_number', models.CharField(blank=True, max_length=20)),
                ('police_email', models.EmailField(blank=True, max_length=254)),
                ('hood_pic', cloudinary.models.CloudinaryField(default='image/upload/v1627343010/neighborhood1_cj2fyx.jpg', max_length=255, verbose_name='images')),
            ],
        ),
    ]
